# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

GCC_BIN = 
PROJECT = mbed_blinky
OBJECTS = ./mbed-src/targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_GCC_ARM/startup_LPC17xx.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M3/TOOLCHAIN_GCC/HAL_CM3.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M3/TOOLCHAIN_GCC/SVC_Table.o \
	./mbed-src/targets/cmsis/TARGET_NXP/TARGET_LPC176X/system_LPC17xx.o \
	./mbed-src/targets/cmsis/TARGET_NXP/TARGET_LPC176X/cmsis_nvic.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/analogin_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/spi_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/gpio_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/i2c_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/analogout_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/rtc_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/can_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/port_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/pwmout_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/serial_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/sleep.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/gpio_irq_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/pinmap.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/ethernet_api.o \
	./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/us_ticker.o \
	./mbed-src/common/wait_api.o \
	./mbed-src/common/board.o \
	./mbed-src/common/semihost_api.o \
	./mbed-src/common/pinmap_common.o \
	./mbed-src/common/us_ticker_api.o \
	./mbed-src/common/assert.o \
	./mbed-src/common/gpio.o \
	./mbed-src/common/error.o \
	./mbed-src/common/mbed_interface.o \
	./mbed-src/common/rtc_time.o \
	./EthernetInterface/lwip-eth/arch/TARGET_NXP/lpc17_emac.o \
	./EthernetInterface/lwip-eth/arch/TARGET_NXP/lpc_phy_dp83848.o \
	./EthernetInterface/lwip-sys/arch/sys_arch.o \
	./EthernetInterface/lwip-sys/arch/checksum.o \
	./EthernetInterface/lwip-sys/arch/memcpy.o \
	./EthernetInterface/lwip/api/api_msg.o \
	./EthernetInterface/lwip/api/netbuf.o \
	./EthernetInterface/lwip/api/tcpip.o \
	./EthernetInterface/lwip/api/netdb.o \
	./EthernetInterface/lwip/api/netifapi.o \
	./EthernetInterface/lwip/api/err.o \
	./EthernetInterface/lwip/api/api_lib.o \
	./EthernetInterface/lwip/api/sockets.o \
	./EthernetInterface/lwip/core/udp.o \
	./EthernetInterface/lwip/core/memp.o \
	./EthernetInterface/lwip/core/timers.o \
	./EthernetInterface/lwip/core/netif.o \
	./EthernetInterface/lwip/core/tcp_in.o \
	./EthernetInterface/lwip/core/init.o \
	./EthernetInterface/lwip/core/pbuf.o \
	./EthernetInterface/lwip/core/def.o \
	./EthernetInterface/lwip/core/dhcp.o \
	./EthernetInterface/lwip/core/mem.o \
	./EthernetInterface/lwip/core/raw.o \
	./EthernetInterface/lwip/core/tcp.o \
	./EthernetInterface/lwip/core/tcp_out.o \
	./EthernetInterface/lwip/core/stats.o \
	./EthernetInterface/lwip/core/dns.o \
	./EthernetInterface/lwip/core/snmp/msg_out.o \
	./EthernetInterface/lwip/core/snmp/asn1_dec.o \
	./EthernetInterface/lwip/core/snmp/mib_structs.o \
	./EthernetInterface/lwip/core/snmp/msg_in.o \
	./EthernetInterface/lwip/core/snmp/asn1_enc.o \
	./EthernetInterface/lwip/core/snmp/mib2.o \
	./EthernetInterface/lwip/core/ipv4/igmp.o \
	./EthernetInterface/lwip/core/ipv4/ip.o \
	./EthernetInterface/lwip/core/ipv4/ip_addr.o \
	./EthernetInterface/lwip/core/ipv4/autoip.o \
	./EthernetInterface/lwip/core/ipv4/inet_chksum.o \
	./EthernetInterface/lwip/core/ipv4/inet.o \
	./EthernetInterface/lwip/core/ipv4/icmp.o \
	./EthernetInterface/lwip/core/ipv4/ip_frag.o \
	./EthernetInterface/lwip/netif/slipif.o \
	./EthernetInterface/lwip/netif/etharp.o \
	./EthernetInterface/lwip/netif/ethernetif.o \
	./EthernetInterface/lwip/netif/ppp/vj.o \
	./EthernetInterface/lwip/netif/ppp/magic.o \
	./EthernetInterface/lwip/netif/ppp/chpms.o \
	./EthernetInterface/lwip/netif/ppp/ppp_oe.o \
	./EthernetInterface/lwip/netif/ppp/fsm.o \
	./EthernetInterface/lwip/netif/ppp/chap.o \
	./EthernetInterface/lwip/netif/ppp/auth.o \
	./EthernetInterface/lwip/netif/ppp/md5.o \
	./EthernetInterface/lwip/netif/ppp/lcp.o \
	./EthernetInterface/lwip/netif/ppp/ipcp.o \
	./EthernetInterface/lwip/netif/ppp/pap.o \
	./EthernetInterface/lwip/netif/ppp/ppp.o \
	./EthernetInterface/lwip/netif/ppp/randm.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Task.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_MemBox.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Robin.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Mailbox.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_System.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Event.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Semaphore.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Time.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_Mutex.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/rt_List.o \
	./mbed-rtos/rtx/TARGET_CORTEX_M/HAL_CM.o \
	./mbed-src/common/RawSerial.o \
	./mbed-src/common/Stream.o \
	./mbed-src/common/Timeout.o \
	./mbed-src/common/LocalFileSystem.o \
	./mbed-src/common/FunctionPointer.o \
	./mbed-src/common/I2CSlave.o \
	./mbed-src/common/FilePath.o \
	./mbed-src/common/InterruptManager.o \
	./mbed-src/common/BusOut.o \
	./mbed-src/common/Timer.o \
	./mbed-src/common/FileSystemLike.o \
	./mbed-src/common/I2C.o \
	./mbed-src/common/CAN.o \
	./mbed-src/common/SPISlave.o \
	./mbed-src/common/TimerEvent.o \
	./mbed-src/common/Serial.o \
	./mbed-src/common/SPI.o \
	./mbed-src/common/SerialBase.o \
	./mbed-src/common/Ethernet.o \
	./mbed-src/common/retarget.o \
	./mbed-src/common/CallChain.o \
	./mbed-src/common/BusIn.o \
	./mbed-src/common/Ticker.o \
	./mbed-src/common/InterruptIn.o \
	./mbed-src/common/FileLike.o \
	./mbed-src/common/BusInOut.o \
	./mbed-src/common/FileBase.o \
	./EthernetInterface/EthernetInterface.o \
	./EthernetInterface/Socket/Socket.o \
	./EthernetInterface/Socket/UDPSocket.o \
	./EthernetInterface/Socket/Endpoint.o \
	./EthernetInterface/Socket/TCPSocketConnection.o \
	./EthernetInterface/Socket/TCPSocketServer.o \
	./SPI_TFT_ILI9341/SPI_TFT_ILI9341_NUCLEO.o \
	./SPI_TFT_ILI9341/TextDisplay.o \
	./SPI_TFT_ILI9341/GraphicsDisplay.o \
	./SPI_TFT_ILI9341/SPI_TFT_ILI9341.o \
	./SPI_TFT_ILI9341/SPI_TFT_ILI9341_NXP.o \
	./mbed-rtos/rtos/RtosTimer.o \
	./mbed-rtos/rtos/Thread.o ./mbed-rtos/rtos/Mutex.o \
	./mbed-rtos/rtos/Semaphore.o \
	./SDFileSystem/CRC16.o \
	./SDFileSystem/SDFileSystem.o \
	./SDFileSystem/CRC7.o \
	./SDFileSystem/FATFileSystem/FATDirHandle.o \
	./SDFileSystem/FATFileSystem/FATFileHandle.o \
	./SDFileSystem/FATFileSystem/FATFileSystem.o \
	./SDFileSystem/FATFileSystem/ChaN/ccsbcs.o \
	./SDFileSystem/FATFileSystem/ChaN/ff.o \
	./SDFileSystem/FATFileSystem/ChaN/diskio.o 

SHELL_DIR = ./SerialShell
SHELL_OBJS = $(SHELL_DIR)/Shell.o

PRJ_OBJECTS = ./main.o 

HTU21D_DIR = ./HTU21D
HTU21D_OBJECTS = $(HTU21D_DIR)/HTU21D.o

AXTLS_DIR = ./TLS_axTLS
AXTLS_OBJECTS = $(AXTLS_DIR)/axTLS/ssl/asn1.o \
	$(AXTLS_DIR)/axTLS/ssl/asn1.o \
	$(AXTLS_DIR)/axTLS/ssl/openssl.o \
	$(AXTLS_DIR)/axTLS/ssl/p12.o \
	$(AXTLS_DIR)/axTLS/ssl/os_port.o \
	$(AXTLS_DIR)/axTLS/ssl/x509.o \
	$(AXTLS_DIR)/axTLS/ssl/tls1_clnt.o \
	$(AXTLS_DIR)/axTLS/ssl/tls1_svr.o \
	$(AXTLS_DIR)/axTLS/ssl/tls1.o \
	$(AXTLS_DIR)/axTLS/crypto/sha1.o \
	$(AXTLS_DIR)/axTLS/crypto/rsa.o \
	$(AXTLS_DIR)/axTLS/crypto/md2.o \
	$(AXTLS_DIR)/axTLS/crypto/rc4.o \
	$(AXTLS_DIR)/axTLS/crypto/crypto_misc.o \
	$(AXTLS_DIR)/axTLS/crypto/md5.o \
	$(AXTLS_DIR)/axTLS/crypto/aes.o \
	$(AXTLS_DIR)/axTLS/crypto/hmac.o \
	$(AXTLS_DIR)/axTLS/crypto/bigint.o \
	$(AXTLS_DIR)/TLSConnection.o \
 	$(AXTLS_DIR)/CertificateManager.o 

HTTPSCLIENT_DIR = ./HTTPSClient
HTTPSCLIENT_OBJS = $(HTTPSCLIENT_DIR)/HTTPHeader.o \
	$(HTTPSCLIENT_DIR)/HTTPSClient.o 

OAUTH_DIR = ./OAuth
OAUTH_OBJS = $(OAUTH_DIR)/hash.o \
	$(OAUTH_DIR)/oauth.o \
	$(OAUTH_DIR)/sha1.o \
	$(OAUTH_DIR)/oauth_http.o \
	$(OAUTH_DIR)/oauth_data.o 

HTTPClient_DIR = ./HTTPClient
HTTPClient_OBJS = $(HTTPClient_DIR)/HTTPClient.o \
	$(HTTPClient_DIR)/data/HTTPMap.o \
	$(HTTPClient_DIR)/data/HTTPText.o

SYS_OBJECTS = 
INCLUDE_PATHS = -I. -I./mbed-src -I./mbed-src/targets \
	-I./mbed-src/targets/cmsis \
	-I./mbed-src/targets/cmsis/TARGET_NXP \
	-I./mbed-src/targets/cmsis/TARGET_NXP/TARGET_LPC176X \
	-I./mbed-src/targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_GCC_ARM \
	-I./mbed-src/targets/hal -I./mbed-src/targets/hal/TARGET_NXP \
	-I./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X \
	-I./mbed-src/targets/hal/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768 \
	-I./mbed-src/common \
	-I./mbed-src/api \
	-I./mbed-src/hal \
	-I./EthernetInterface \
	-I./EthernetInterface/Socket \
	-I./EthernetInterface/lwip-eth \
	-I./EthernetInterface/lwip-eth/arch \
	-I./EthernetInterface/lwip-eth/arch/TARGET_NXP \
	-I./EthernetInterface/lwip-sys \
	-I./EthernetInterface/lwip-sys/arch \
	-I./EthernetInterface/lwip \
	-I./EthernetInterface/lwip/include \
	-I./EthernetInterface/lwip/include/ipv4 \
	-I./EthernetInterface/lwip/include/ipv4/lwip \
	-I./EthernetInterface/lwip/include/netif \
	-I./EthernetInterface/lwip/include/lwip \
	-I./EthernetInterface/lwip/api \
	-I./EthernetInterface/lwip/core \
	-I./EthernetInterface/lwip/core/snmp \
	-I./EthernetInterface/lwip/core/ipv4 \
	-I./EthernetInterface/lwip/netif \
	-I./EthernetInterface/lwip/netif/ppp \
	-I./SPI_TFT_ILI9341 \
	-I./mbed-rtos \
	-I./mbed-rtos/rtx \
	-I./mbed-rtos/rtx/TARGET_CORTEX_M \
	-I./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M3 \
	-I./mbed-rtos/rtx/TARGET_CORTEX_M/TARGET_M3/TOOLCHAIN_GCC \
	-I./mbed-rtos/rtos \
	-I./SDFileSystem \
	-I./SDFileSystem/FATFileSystem \
	-I./SDFileSystem/FATFileSystem/ChaN \
	-I$(HTU21D_DIR) \
	-I$(AXTLS_DIR) \
	-I$(AXTLS_DIR)/axTLS \
    -I$(AXTLS_DIR)/axTLS/ssl \
	-I$(AXTLS_DIR)/axTLS/crypto \
	-I$(HTTPSCLIENT_DIR) \
	-I$(OAUTH_DIR) \
	-I$(HTTPClient_DIR) \
	-I$(HTTPClient_DIR)/data \
	-I$(SHELL_DIR)/
	


LIBRARY_PATHS = 
LIBRARIES = 
LINKER_SCRIPT = ./mbed-src/targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_GCC_ARM/LPC1768.ld

############################################################################### 
AS      = $(GCC_BIN)arm-none-eabi-as
CC      = $(GCC_BIN)arm-none-eabi-gcc
CPP     = $(GCC_BIN)arm-none-eabi-g++
LD      = $(GCC_BIN)arm-none-eabi-gcc
OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy
OBJDUMP = $(GCC_BIN)arm-none-eabi-objdump
SIZE 	= $(GCC_BIN)arm-none-eabi-size

CPU = -mcpu=cortex-m3 -mthumb
CC_FLAGS = $(CPU) -c -g -fno-common -fmessage-length=0 -Wall -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer
CC_FLAGS += -MMD -MP
CC_SYMBOLS = -DTARGET_LPC1768 -DTARGET_M3 -DTARGET_CORTEX_M -DTARGET_NXP -DTARGET_LPC176X -DTARGET_MBED_LPC1768 -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_GCC -D__CORTEX_M3 -DARM_MATH_CM3 -DMBED_BUILD_TIMESTAMP=1429585436.88 -D__MBED__=1 

LD_FLAGS = $(CPU) -Wl,--gc-sections --specs=nano.specs -u _printf_float -u _scanf_float -Wl,--wrap,main
LD_FLAGS += -Wl,-Map=$(PROJECT).map,--cref
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys

ifeq ($(DEBUG), 1)
  CC_FLAGS += -DDEBUG -O0
else
  CC_FLAGS += -DNDEBUG -Os
endif

all: $(PROJECT).bin $(PROJECT).hex 

clean:
	rm -f $(PROJECT).bin $(PROJECT).elf $(PROJECT).hex $(PROJECT).map $(PROJECT).lst $(OBJECTS) $(PRJ_OBJECTS) $(HTU21D_OBJECTS) $(AXTLS_OBJECTS) $(HTTPSCLIENT_OBJS) $(OAUTH_OBJS) $(HTTPClient_OBJS) $(SHELL_OBJS) $(DEPS)

%.o:%.s
	$(AS) $(CPU) -o $@ $<

%.o:%.c
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDE_PATHS) -o $@ $<

%.o:%.cpp
	$(CPP) $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu++98 -fno-rtti $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PRJ_OBJECTS) $(HTU21D_OBJECTS) $(AXTLS_OBJECTS) $(HTTPSCLIENT_OBJS) $(OAUTH_OBJS) $(HTTPClient_OBJS) $(SHELL_OBJS)
	$(LD) $(LD_FLAGS) -T$(LINKER_SCRIPT) $(LIBRARY_PATHS) -o $@ $^ $(LIBRARIES) $(LD_SYS_LIBS) $(LIBRARIES) $(LD_SYS_LIBS)
	@echo ""
	@echo "*****"
	@echo "***** You must modify vector checksum value in *.bin and *.hex files."
	@echo "*****"
	@echo ""
	$(SIZE) $@

$(PROJECT).bin: $(PROJECT).elf
	@$(OBJCOPY) -O binary $< $@

$(PROJECT).hex: $(PROJECT).elf
	@$(OBJCOPY) -O ihex $< $@

$(PROJECT).lst: $(PROJECT).elf
	@$(OBJDUMP) -Sdh $< > $@

lst: $(PROJECT).lst

size:
	$(SIZE) $(PROJECT).elf

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d) $(PRJ_OBJECTS:.o=.d) $(HTU21D_OBJECTS:.o=.d) $(AXTLS_OBJECTS:.o=.d) $(OAUTH_OBJS:.o=.d) $(HTTPClient_OBJS:.o=.d)
-include $(DEPS)
